In [2]:
import numpy as np



def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1/(1+np.exp(-x))

# Network size
N_input = 4
N_hidden = 3
N_output = 2

np.random.seed(42)
# Make some fake data
X = np.random.randn(4)

weights_input_to_hidden = np.random.normal(0, scale=0.1, size=(N_input, N_hidden))
weights_hidden_to_output = np.random.normal(0, scale=0.1, size=(N_hidden, N_output))


# TODO: Make a forward pass through the network
"""
Calculate the input to the hidden layer.
Calculate the hidden layer output.
Calculate the input to the output layer.
Calculate the output of the network.
"""

hidden_layer_in = np.dot(X, weights_input_to_hidden)
hidden_layer_out = sigmoid(hidden_layer_in)

print('Hidden-layer Output:')
print(hidden_layer_out)

output_layer_in = np.dot(hidden_layer_out,weights_hidden_to_output)
output_layer_out = sigmoid(output_layer_in)

print('Output-layer Output:')
print(output_layer_out)

Hidden-layer Output:
[0.41492192 0.42604313 0.5002434 ]
Output-layer Output:
[0.49815196 0.48539772]


In [105]:
import numpy as np
a= np.array([0, 1, 2, 3])

res=   a / (np.max(a)* 5/4 ) +0.1


print(res)

[0.1        0.36666667 0.63333333 0.9       ]


In [111]:
import tensorflow as tf

tf.random.truncated_normal((100,100))

<tf.Tensor: shape=(100, 100), dtype=float32, numpy=
array([[ 0.21698466,  0.03346488,  0.17558704, ..., -1.5355802 ,
        -0.14533609, -0.7988997 ],
       [-0.02265811, -0.4233101 ,  1.5388341 , ..., -0.2482151 ,
         0.48127067, -0.74237263],
       [-1.5996301 ,  0.69718677, -0.50641507, ...,  0.6814653 ,
        -1.3826973 , -0.64377993],
       ...,
       [ 1.7745442 ,  1.1449605 ,  0.9549685 , ..., -0.06310686,
         0.97111696,  0.5463382 ],
       [ 1.867164  ,  0.72270876,  0.68102145, ...,  0.560236  ,
         0.8979679 , -1.0052506 ],
       [-0.5397844 ,  0.19410127, -0.17456973, ...,  0.06829837,
        -0.05674382,  0.31901225]], dtype=float32)>

In [157]:

#from numpy import ones
#import numpy as np

# check the difference

a=np.random.randn(10,5)
b = np.ones(10)

print(a)

[[-1.57102917 -0.22578375 -0.05574025 -2.16071089  1.48516325]
 [ 0.47578461 -0.80866266 -0.38448098  0.17148085 -2.34343208]
 [-0.03383211  0.3739352  -1.00865134 -0.11766377  0.13970821]
 [ 2.15529129 -0.03953447  1.161995    0.84883041 -2.06967312]
 [-0.54459344  0.45909176  1.26091374  0.33611088 -2.29250842]
 [-0.1519718   0.43373993 -0.28214543 -0.26407361  0.4653402 ]
 [-0.24505217  0.73148036 -1.12520633 -0.68858622  1.17862667]
 [ 0.81110634 -0.10552199 -0.88314755  2.16844229  0.79538673]
 [-1.12678428  0.64962466  0.44565079  0.49137497  2.69782594]
 [-0.38635297 -1.20223196  1.94193135  1.83729038  0.62072311]]


In [161]:
import urllib.request

import sklearn 
#resample(train_features, train_labels, n_samples=docker_size_limit)

sklearn.utils.resample ( a,b,  n_samples=5)

[array([[-0.24505217,  0.73148036, -1.12520633, -0.68858622,  1.17862667],
        [ 0.81110634, -0.10552199, -0.88314755,  2.16844229,  0.79538673],
        [-0.1519718 ,  0.43373993, -0.28214543, -0.26407361,  0.4653402 ],
        [ 0.81110634, -0.10552199, -0.88314755,  2.16844229,  0.79538673],
        [ 2.15529129, -0.03953447,  1.161995  ,  0.84883041, -2.06967312]]),
 array([1., 1., 1., 1., 1.])]